import type { BankProfile } from "./types";

// In-code mirror of the unverified presets seeded by 0053. Used when the
// database list is unavailable (tests, a first upload before any profile
// is loaded) -- keep in lockstep with the migration's insert.
const base = {
  id: null,
  orgId: null,
  dateFormat: "dd/MM/yyyy",
  decimalSeparator: ",",
  verified: false,
} as const;

export const BUILTIN_PROFILES: BankProfile[] = [
  {
    ...base,
    bankCode: "piraeus",
    name: "Τράπεζα Πειραιώς (CSV)",
    fileKind: "csv",
    encoding: "windows-1253",
    delimiter: ";",
    headerSignature: ["ΗΜΕΡΟΜΗΝΙΑ", "ΠΕΡΙΓΡΑΦΗ", "ΧΡΕΩΣΗ", "ΠΙΣΤΩΣΗ"],
    columnMap: {
      date: "ΗΜΕΡΟΜΗΝΙΑ",
      value_date: ["ΗΜ/ΝΙΑ ΑΞΙΑΣ", "ΑΞΙΑ"],
      description: "ΠΕΡΙΓΡΑΦΗ",
      debit: "ΧΡΕΩΣΗ",
      credit: "ΠΙΣΤΩΣΗ",
      balance: "ΥΠΟΛΟΙΠΟ",
      reference: ["ΑΡ. ΣΥΝΑΛΛΑΓΗΣ", "ΚΩΔΙΚΟΣ ΣΥΝΑΛΛΑΓΗΣ"],
    },
    signMode: "debit_credit",
    debitMarkers: [],
    footerPattern: "^(ΣΥΝΟΛ|ΥΠΟΛΟΙΠΟ)",
  },
  {
    ...base,
    bankCode: "nbg",
    name: "Εθνική Τράπεζα (CSV)",
    fileKind: "csv",
    encoding: "windows-1253",
    delimiter: ";",
    headerSignature: ["ΗΜΕΡΟΜΗΝΙΑ", "ΠΕΡΙΓΡΑΦΗ", "ΠΟΣΟ", "ΠΡΟΣΗΜΟ ΠΟΣΟΥ"],
    columnMap: {
      date: "ΗΜΕΡΟΜΗΝΙΑ",
      value_date: ["ΗΜΕΡΟΜΗΝΙΑ ΑΞΙΑΣ", "ΗΜ/ΝΙΑ ΑΞΙΑΣ"],
      description: "ΠΕΡΙΓΡΑΦΗ",
      amount: "ΠΟΣΟ",
      direction: "ΠΡΟΣΗΜΟ ΠΟΣΟΥ",
      balance: ["ΛΟΓΙΣΤΙΚΟ ΥΠΟΛΟΙΠΟ", "ΥΠΟΛΟΙΠΟ"],
      reference: ["ΑΡΙΘΜΟΣ ΣΥΝΑΛΛΑΓΗΣ", "ΑΡ. ΣΥΝΑΛΛΑΓΗΣ"],
      counterparty: ["ΟΝΟΜΑ ΑΝΤΙΣΥΜΒΑΛΛΟΜΕΝΟΥ", "ΑΝΤΙΣΥΜΒΑΛΛΟΜΕΝΟΣ"],
      counterparty_iban: ["IBAN ΑΝΤΙΣΥΜΒΑΛΛΟΜΕΝΟΥ"],
    },
    signMode: "direction_column",
    debitMarkers: ["Χ", "ΧΡΕΩΣΗ", "D", "-"],
    footerPattern: "^(ΣΥΝΟΛ|ΥΠΟΛΟΙΠΟ)",
  },
  {
    ...base,
    bankCode: "eurobank",
    name: "Eurobank (XLSX)",
    fileKind: "xlsx",
    encoding: "utf-8",
    delimiter: null,
    headerSignature: ["ΗΜΕΡΟΜΗΝΙΑ", "ΠΕΡΙΓΡΑΦΗ", "ΠΟΣΟ", "ΥΠΟΛΟΙΠΟ"],
    columnMap: {
      date: ["ΗΜΕΡΟΜΗΝΙΑ", "ΗΜΕΡΟΜΗΝΙΑ ΣΥΝΑΛΛΑΓΗΣ"],
      value_date: "ΗΜΕΡΟΜΗΝΙΑ ΑΞΙΑΣ",
      description: "ΠΕΡΙΓΡΑΦΗ",
      amount: "ΠΟΣΟ",
      balance: "ΥΠΟΛΟΙΠΟ",
      reference: ["ΑΡΙΘΜΟΣ ΑΝΑΦΟΡΑΣ", "ΑΙΤΙΟΛΟΓΙΑ"],
    },
    signMode: "signed",
    debitMarkers: [],
    footerPattern: "^(ΣΥΝΟΛ|ΥΠΟΛΟΙΠΟ)",
  },
  {
    ...base,
    bankCode: "alpha",
    name: "Alpha Bank (CSV)",
    fileKind: "csv",
    encoding: "windows-1253",
    delimiter: ";",
    headerSignature: ["ΗΜ/ΝΙΑ", "ΑΙΤΙΟΛΟΓΙΑ", "ΠΟΣΟ"],
    columnMap: {
      date: "ΗΜ/ΝΙΑ",
      value_date: ["ΗΜ/ΝΙΑ ΑΞΙΑΣ", "ΑΞΙΑ"],
      description: "ΑΙΤΙΟΛΟΓΙΑ",
      amount: "ΠΟΣΟ",
      balance: "ΥΠΟΛΟΙΠΟ",
      reference: ["ΚΩΔ. ΣΥΝΑΛΛΑΓΗΣ", "ΑΡ. ΣΥΝΑΛΛΑΓΗΣ"],
    },
    signMode: "trailing_minus",
    debitMarkers: [],
    footerPattern: "^(ΣΥΝΟΛ|ΥΠΟΛΟΙΠΟ)",
  },
  {
    ...base,
    bankCode: "generic",
    name: "Γενική μορφή (ημερομηνία / περιγραφή / ποσό)",
    fileKind: "csv",
    encoding: "utf-8",
    delimiter: null,
    headerSignature: ["ΗΜΕΡΟΜΗΝΙΑ", "ΠΕΡΙΓΡΑΦΗ", "ΠΟΣΟ"],
    columnMap: {
      date: ["ΗΜΕΡΟΜΗΝΙΑ", "DATE"],
      value_date: ["ΗΜΕΡΟΜΗΝΙΑ ΑΞΙΑΣ", "VALUE DATE"],
      description: ["ΠΕΡΙΓΡΑΦΗ", "ΑΙΤΙΟΛΟΓΙΑ", "DESCRIPTION"],
      amount: ["ΠΟΣΟ", "AMOUNT"],
      balance: ["ΥΠΟΛΟΙΠΟ", "BALANCE"],
      reference: ["ΑΝΑΦΟΡΑ", "REFERENCE"],
    },
    signMode: "signed",
    debitMarkers: [],
    footerPattern: "^(ΣΥΝΟΛ|ΥΠΟΛΟΙΠΟ|TOTAL)",
  },
];
