# bake_values.ps1
#
# back_office_operations.xlsx is generated by generate_workbook_v2.py using
# openpyxl, which writes formulas but never their computed results. Loading
# the file with openpyxl(data_only=True) therefore returns None for every
# derived cell (Μήνας, Πληρωμένο Μέχρι Σήμερα, ΦΠΑ net position, Τρέχον
# Υπόλοιπο, contact rollups -- everything). That makes the file useless as a
# migration-verification reference as it stands.
#
# This script drives real Excel via COM (same approach as build_pivots.ps1)
# to force a full recalculation and save the result WITH cached values, so
# verify_migration.py has real numbers to reconcile against.
#
# Run this ONCE, with Excel closed, before tools/migrate_workbook.py:
#   py generate_workbook_v2.py
#   powershell -File tools/bake_values.ps1
#   py tools/migrate_workbook.py --dry-run

param(
    [string]$SourceFile = "back_office_operations.xlsx",
    [string]$OutFile    = "back_office_operations_values.xlsx"
)
$ErrorActionPreference = "Stop"

$root = Split-Path $PSScriptRoot -Parent
$sourcePath = Join-Path $root $SourceFile
$outPath    = Join-Path $root $OutFile

if (-not (Test-Path $sourcePath)) {
    throw "Source file not found: $sourcePath -- run generate_workbook_v2.py first."
}

$xlCalculationAutomatic = -4105

$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false
try {
    $excel.Calculation = $xlCalculationAutomatic
    $wb = $excel.Workbooks.Open($sourcePath)

    $wb.Application.CalculateFullRebuild()

    # SaveAs under a new name -- keep the openpyxl-generated source untouched
    # so re-running generate_workbook_v2.py is never blocked by a locked file.
    $wb.SaveAs($outPath)
    $wb.Close($false)

    Write-Host "Baked values written to $outPath"
}
finally {
    $excel.Quit()
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
}
